# Generated by Django 5.2.1 on 2025-05-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="default_meal_status",
            field=models.BooleanField(default=True),
        ),
    ]
