# Generated by Django 5.2.1 on 2025-06-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_default_meal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="default_prefers_beef",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="default_prefers_fish",
            field=models.BooleanField(default=True),
        ),
    ]
