# Generated by Django 5.2.1 on 2025-08-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_default_prefers_beef_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklymenu",
            name="breakfast",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="dinner",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="lunch",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
