# Generated by Django 5.2.1 on 2025-08-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_complain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailymealstatus",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dailymealstatus",
            name="status",
        ),
        migrations.RemoveField(
            model_name="weeklymenu",
            name="alternate_cost",
        ),
        migrations.RemoveField(
            model_name="weeklymenu",
            name="base_cost",
        ),
        migrations.RemoveField(
            model_name="weeklymenu",
            name="breakfast",
        ),
        migrations.RemoveField(
            model_name="weeklymenu",
            name="dinner",
        ),
        migrations.RemoveField(
            model_name="weeklymenu",
            name="includes_beef",
        ),
        migrations.RemoveField(
            model_name="weeklymenu",
            name="includes_fish",
        ),
        migrations.RemoveField(
            model_name="weeklymenu",
            name="lunch",
        ),
        migrations.RemoveField(
            model_name="weeklymenu",
            name="meal_items",
        ),
        migrations.AddField(
            model_name="dailymealstatus",
            name="breakfast_on",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dailymealstatus",
            name="dinner_on",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dailymealstatus",
            name="lunch_on",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dailymealstatus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="breakfast_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="breakfast_main",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="dinner_alternate",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="dinner_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="dinner_main",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="lunch_alternate",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="lunch_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="lunch_main",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
