# Generated by Django 5.2.1 on 2025-09-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_remove_dailymealstatus_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklymenu",
            name="dinner_contains_beef",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="dinner_contains_fish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="dinner_cost_alternate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="lunch_contains_beef",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="lunch_contains_fish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="weeklymenu",
            name="lunch_cost_alternate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="weeklymenu",
            name="breakfast_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="weeklymenu",
            name="dinner_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="weeklymenu",
            name="lunch_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
