# Generated by Django 5.2.1 on 2025-10-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_weeklymenureview"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdetails",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
