# Generated by Django 5.2.1 on 2025-09-14 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyMenuProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("breakfast_main", models.CharField(blank=True, max_length=100)),
                (
                    "breakfast_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("lunch_main", models.CharField(blank=True, max_length=100)),
                (
                    "lunch_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("lunch_contains_beef", models.BooleanField(default=False)),
                ("lunch_contains_fish", models.BooleanField(default=False)),
                ("dinner_main", models.CharField(blank=True, max_length=100)),
                (
                    "dinner_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("dinner_contains_beef", models.BooleanField(default=False)),
                ("dinner_contains_fish", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
