# Generated by Django 5.2.1 on 2025-10-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0001_initial"),
        ("students", "0007_weeklymenu_dinner_contains_beef_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklymenuproposal",
            name="linked_menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposals",
                to="students.weeklymenu",
            ),
        ),
    ]
