# Generated by Django 5.2.1 on 2025-10-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0002_weeklymenuproposal_linked_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklymenuproposal",
            name="dinner_alternate",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weeklymenuproposal",
            name="dinner_cost_alternate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="weeklymenuproposal",
            name="lunch_alternate",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="weeklymenuproposal",
            name="lunch_cost_alternate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
