# Generated by Django 5.2.1 on 2025-10-10 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0003_weeklymenuproposal_dinner_alternate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklymenuproposal",
            name="week_start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
