# Generated by Django 5.2.1 on 2025-10-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0005_managerprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="managerprofile",
            old_name="national_id",
            new_name="nid",
        ),
    ]
