# Generated by Django 5.2.1 on 2025-10-28 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0007_specialmealrequest"),
        ("students", "0010_studentdetails_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("main", "Main Token"),
                            ("alternate", "Alternate Token"),
                        ],
                        max_length=10,
                    ),
                ),
                ("collected", models.BooleanField(default=False)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tokens_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "date", "meal_type"),
                        name="unique_token_per_meal_per_day",
                    )
                ],
            },
        ),
    ]
