# Generated by Django 5.2.1 on 2025-11-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0008_mealtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="managerprofile",
            name="hall_responsibilities",
            field=models.TextField(blank=True, null=True),
        ),
    ]
