# Generated by Django 5.2.1 on 2025-11-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0009_managerprofile_hall_responsibilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealtoken",
            name="barcode",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="mealtoken",
            name="expiry_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mealtoken",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
