# Generated by Django 5.2.1 on 2025-11-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0010_mealtoken_barcode_mealtoken_expiry_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealtoken",
            name="barcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
