# Generated by Django 5.2.1 on 2025-11-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managers", "0011_alter_mealtoken_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealtoken",
            name="barcode",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
