# Generated by Django 5.2.1 on 2025-10-25 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="student",
            new_name="voted_by",
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="votepoll",
            name="is_active",
        ),
        migrations.AddField(
            model_name="vote",
            name="poll",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="votes.votepoll",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vote",
            name="voted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="voteoption",
            name="option_text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="votepoll",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_polls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="votepoll",
            name="expires_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("poll", "voted_by")},
        ),
    ]
