# Generated by Django 5.2.1 on 2025-10-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votes", "0002_rename_student_vote_voted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="votepoll",
            name="floor_number",
            field=models.CharField(
                blank=True,
                help_text="Required if scope = floor",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="votepoll",
            name="scope",
            field=models.CharField(
                choices=[
                    ("universal", "Universal (All Students)"),
                    ("floor", "Specific Floor"),
                ],
                default="universal",
                max_length=20,
            ),
        ),
    ]
