# Generated by Django 5.2.1 on 2025-10-27 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("teacher", "Teacher"), ("staff", "Staff")],
                        default="teacher",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lecturer", "Lecturer"),
                            ("assistant_professor", "Assistant Professor"),
                            ("associate_professor", "Associate Professor"),
                            ("professor", "Professor"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "hall_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("provost", "Provost"),
                            ("assistant_provost", "Assistant Provost"),
                            ("resident_teacher", "Resident Teacher"),
                            ("office_staff", "Office Staff"),
                            ("support_staff", "Support Staff"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("hall_responsibilities", models.TextField(blank=True, null=True)),
                (
                    "assigned_floor",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="admin_photos/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
