# Generated by Django 5.2.1 on 2025-10-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminprofile",
            name="hall_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("provost", "Provost"),
                    ("assistant_provost", "Assistant Provost"),
                    ("house_tutor", "House Tutor"),
                    ("office_staff", "Office Staff"),
                    ("support_staff", "Support Staff"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
