# Generated by Django 5.2.1 on 2025-10-24 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="notice",
            old_name="content",
            new_name="message",
        ),
        migrations.AddField(
            model_name="notice",
            name="posted_by",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notice",
            name="visible_to_students",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="notices/"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
